### ISSUE TITLE
Problem with props deconstructing and functional component returning expression

### ISSUE THREAD

**Issue by pekala** [billyvg/codemod-proptypes-to-flow#7]
Trying to mod this file:
```javascript
// @flow
import React, { PropTypes } from 'react';
const MyComponent = ({ hello }) => <div>{hello}</div>;
MyComponent.propTypes = {
    hello: PropTypes.string.isRequired,
};
export default MyComponent;
```
Gives a `Transformation error` 
<details>

```ERR ./example/MyComponent.js Transformation error
TypeError: Cannot read property 'unshift' of undefined
    at insertTypeIdentifierInFunction (/Users/penso/Dev/codemod-proptypes-to-flow/src/transformers/functional.js:51:5)
    at NodePath.<anonymous> (/Users/penso/Dev/codemod-proptypes-to-flow/src/transformers/functional.js:90:7)
    at __paths.forEach (/Users/penso/.npm-packages/lib/node_modules/jscodeshift/dist/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/Users/penso/.npm-packages/lib/node_modules/jscodeshift/dist/Collection.js:75:18)
    at /Users/penso/Dev/codemod-proptypes-to-flow/src/transformers/functional.js:87:6
    at Array.forEach (native)
    at transformFunctionalComponents (/Users/penso/Dev/codemod-proptypes-to-flow/src/transformers/functional.js:68:14)
    at transformer (/Users/penso/Dev/codemod-proptypes-to-flow/src/index.js:30:35)
```

</details>

but changing the file to 

```javascript
// @flow
import React, { PropTypes } from 'react';
const MyComponent = props => <div>{props.hello}</div>;
MyComponent.propTypes = {
    hello: PropTypes.string.isRequired,
};
export default MyComponent;
```
works as expected (`PropTypes` import remaining is expected to not be handled, according to readme), i.e.

```javascript
// @flow
import React, { PropTypes } from 'react';
export type Props = { hello: string };
const MyComponent = props: Props => <div>{props.hello}</div>;
export default MyComponent;
```

**Comment by pekala** [comment]
I guess that the problem is that here: https://github.com/billyvg/codemod-proptypes-to-flow/blob/master/src/transformers/functional.js#L51 you're assuming that the function will have a body where you can inject the spread, while in my example the function returns an expression.
